### ISSUE TITLE
The rank is not being updated

### ISSUE THREAD

**Issue by FoxyMC-MCBE** [r3pt1s/GroupSystem#10]
When I change a player's rank, it doesn't get updated, even when the player leaves and rejoins the server.

**Comment by r3pt1s** [comment]
Make sure that the group you have been given to the player is higher in the groups file than the current group

**Comment by r3pt1s** [comment]
For example, you have this groups config:

```
Player: ...
Owner: ...
```

And you want to give a player the Owner group, they won't receive the groups because it has a lower ranking than the Player group. 
The fixed one would be: 

```
Owner: ...
Player: ...
```
